# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork
  development:
    cmd_settings:
      accounts: 100

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0

# path remapping to support OpenZepplin imports with NPM-style path
# remapping has a bug when remapping multiple paths from same github root
# https://github.com/eth-brownie/brownie/issues/893
# compiler:
#   solc:
#     remappings:
#       - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
#       - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@3.4.0"

reports:
  exclude_paths:
    - contracts/test/Token.sol
    - contracts/test/ProfitStrategy.sol

dev_deployment_artifacts: True